# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Cosmin Gherman/Desktop/SSC_lab/SSC_proiect2/SSC_proiect2.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Cosmin Gherman/Desktop/SSC_lab/SSC_proiect2/SSC_proiect2.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Cosmin Gherman/Desktop/SSC_lab/SSC_proiect2/SSC_proiect2.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Cosmin Gherman/Desktop/SSC_lab/SSC_proiect2/SSC_proiect2.srcs/sources_1/imports/new/I2CModule.vhd}
  {C:/Users/Cosmin Gherman/Desktop/SSC_lab/SSC_proiect2/SSC_proiect2.srcs/sources_1/imports/Downloads/debouncer.vhd}
  {C:/Users/Cosmin Gherman/Desktop/SSC_lab/SSC_proiect2/SSC_proiect2.srcs/sources_1/new/uart_tx.vhd}
  {C:/Users/Cosmin Gherman/Desktop/SSC_lab/SSC_proiect2/SSC_proiect2.srcs/sources_1/new/ConvertorDecAsc.vhd}
  {C:/Users/Cosmin Gherman/Desktop/SSC_lab/SSC_proiect2/SSC_proiect2.srcs/sources_1/imports/new/SSD.vhd}
  {C:/Users/Cosmin Gherman/Desktop/SSC_lab/SSC_proiect2/SSC_proiect2.srcs/sources_1/imports/new/temp_senzor.vhd}
  {C:/Users/Cosmin Gherman/Desktop/SSC_lab/SSC_proiect2/SSC_proiect2.srcs/sources_1/imports/new/UART_16.vhd}
  {C:/Users/Cosmin Gherman/Desktop/SSC_lab/SSC_proiect2/SSC_proiect2.srcs/sources_1/imports/new/top_module.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Cosmin Gherman/Desktop/SSC_lab/SSC_proiect2/SSC_proiect2.srcs/constrs_1/imports/new/nexys4_cosntr.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Cosmin Gherman/Desktop/SSC_lab/SSC_proiect2/SSC_proiect2.srcs/constrs_1/imports/new/nexys4_cosntr.xdc}}]


synth_design -top top_module -part xc7a100tcsg324-1 -flatten_hierarchy none -directive RuntimeOptimized


write_checkpoint -force -noxdef top_module.dcp

catch { report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb }
